//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.13 at 09:51:58 PM CET 
//


package ch.zhaw.gpi.greetings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.zhaw.gpi.greetings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.zhaw.gpi.greetings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetGreetingWithDateRequest }
     * 
     */
    public GetGreetingWithDateRequest createGetGreetingWithDateRequest() {
        return new GetGreetingWithDateRequest();
    }

    /**
     * Create an instance of {@link GetGreetingWithDateResponse }
     * 
     */
    public GetGreetingWithDateResponse createGetGreetingWithDateResponse() {
        return new GetGreetingWithDateResponse();
    }

}
