//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.13 at 09:51:58 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.zhaw.ch/gpi/greetings", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ch.zhaw.gpi.greetings;
